import {Link} from 'react-router-dom'
import {useEffect,useState} from 'react'
import {api} from '../api/client'
import ItemCard from '../components/ItemCard'
import Icon from '../components/Icon'
import Report from './Report'
import {useAuth} from '../context/AuthContext'
export default function Home(){const {isAuthenticated}=useAuth();const [items,setItems]=useState([]);useEffect(()=>{api.getItems({status:'active',limit:6}).then(setItems).catch(()=>{})},[]);return <>
 <section className="hero"><div className="container hero-grid"><div><span className="kicker">CAMPUS LOST & FOUND</span><h1>Lost something?<br/><em>Let’s find it.</em></h1><p className="hero-copy">Report what went missing, browse what has been found, and let the matching engine surface the most likely connection.</p><div className="hero-actions"><a className="btn btn-primary" href="#new-report">Report an item <Icon name="arrow" size={17}/></a><Link className="btn btn-ghost" to="/found">Browse found items</Link></div><div className="trust"><Icon name="shield" size={17}/><span>Protected student session · backend-verified matching</span></div></div><div className="hero-card"><div className="orbit orbit-a"/><div className="orbit orbit-b"/><div className="bean-illustration">●</div><div className="hero-card-note"><span>AI MATCHING</span><strong>Describe it. We connect it.</strong><small>Location · time · text · image signals</small></div></div></div></section>
 <section className="container section"><div className="section-head"><div><span className="kicker">LIVE BOARD</span><h2>Recently reported</h2></div><Link to="/found" className="text-link">See all <Icon name="arrow" size={16}/></Link></div>{items.length?<div className="grid">{items.map(i=><ItemCard key={i.id} item={i}/>)}</div>:<div className="board-placeholder"><strong>Your campus board starts here.</strong><span>Once the backend has active reports, they will appear on this board.</span></div>}</section>
 <section id="new-report" className="container section home-report"><div className="section-head"><div><span className="kicker">QUICK REPORT</span><h2>Enter a new report</h2><p className="hero-copy">Start a lost or found report directly from the homepage.</p></div></div>{isAuthenticated?<Report/>:<div className="report-card"><h3>Sign in to enter a report</h3><p>Your authenticated campus account is required before a report can be submitted.</p><Link className="btn btn-primary" to="/login">Sign in <Icon name="arrow" size={17}/></Link></div>}</section><section className="process"><div className="container"><div className="section-head"><div><span className="kicker">HOW IT WORKS</span><h2>Three steps to reunion</h2></div></div><div className="steps"><div><b>01</b><h3>Report</h3><p>Add a clear description, location, time and optional image.</p></div><div><b>02</b><h3>Match</h3><p>The backend ranks found items against your lost report.</p></div><div><b>03</b><h3>Claim</h3><p>Choose the likely match and send a claim for review.</p></div></div></div></section>
 </>}
